config/routes.rb
RaffisSite::Application.routes.draw do
  
  root "static_pages#home"
  match '/help', to: 'static_pages#help', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/ref', to: 'static_pages#ref', via: 'get'
  match '/portfolio', to: 'static_pages#portfolio', via: 'get'
  

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RaffisSite</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "sample app", '#', id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Home",    root_path%></li>
              <li><%= link_to "refferences",    ref_path%></li>
              <li><%= link_to "Portfolio", portfolio_path %></li>
              <li><%= link_to "help", help_path %></li>
              <li><%= link_to "Portfolio", contact_path %></li>
            </ul>
          </nav>
        </div>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>

</body>
</html>

app/views/static_pages/contact.html.erb
<!DOCTYPE html>
<h1>Contact info</h1>
<p> Here is all my contact information </p>

app/views/static_pages/help.html.erb
<!DOCTYPE html>
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<!DOCTYPE html>
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>
<p>
	put all the text in here !!
</p>

app/views/static_pages/portfolio.html.erb
<!DOCTYPE html>
<h1>Portfolio</h1>
<p>
Here goes all the amazing things i have done like figuring out how the end of line
shortcut works on a mac

</p>

app/views/static_pages/ref.html.erb
<!-- <% provide(:title, 'Refferences')%>
<%=yield(:title) %>-->
-->
<!DOCTYPE html>
<h1>References</h1>
<p>
  All The people That can say good things about me
</p>